### ISSUE TITLE
Errors with Kodi 19 UWP

### ISSUE THREAD

**Issue by Weasy666** [tbrek/plugin.video.iptv.recorder#4]
Hi there! Thank you for "picking up" this plugin and for doing some maintenance on it.
I am using the Kodi 19 UWP app from the Microsoft store and the newest Windows 10 version.
I installed your fork with "Install from zip file" and pointed it to my installed `ffmpeg.exe`. I then tried to use it to record a stream, but got an error popup. Here the error messages from the log file.

```
2021-03-21 15:00:24.977 T:4768    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: cannot use a string pattern on a bytes-like object
                                                   Traceback (most recent call last):
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3455, in <module>
                                                       plugin.run()
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 338, in run
                                                       items = self._dispatch(self.request.path)
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 312, in _dispatch
                                                       listitems = view_func(**items)
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 2529, in full_service
                                                       xmltv()
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3049, in xmltv
                                                       match = re.findall('<programme(.*?)</programme>', data, flags=(re.I|re.DOTALL))
                                                     File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.500.0_x64__4n2hpmxwrvr6p\system\python\Lib\re.py", line 241, in findall
                                                       return _compile(pattern, flags).findall(string)
                                                   TypeError: cannot use a string pattern on a bytes-like object
                                                   -->End of Python script error report<--
                                                   
2021-03-21 15:00:25.022 T:4768     INFO <general>: Python interpreter stopped
2021-03-21 15:00:42.348 T:9148     INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2021-03-21 15:00:52.822 T:9148  WARNING <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2021-03-21 15:01:02.072 T:9148    ERROR <general>: Skipped 2 duplicate messages..
2021-03-21 15:01:02.072 T:9148    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-03-21 15:01:02.108 T:2236     INFO <general>: initializing python engine.
2021-03-21 15:01:03.311 T:2236     INFO <general>: [xbmcswift2] Request for "/" matches rule for function "index"
2021-03-21 15:01:03.311 T:2236  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-21 15:01:03.318 T:2236     INFO <general>: CPythonInvoker(6, C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): script successfully run
2021-03-21 15:01:03.365 T:2236     INFO <general>: Python interpreter stopped
2021-03-21 15:01:14.784 T:10044    INFO <general>: initializing python engine.
2021-03-21 15:01:15.853 T:10044    INFO <general>: [xbmcswift2] Request for "/recordings" matches rule for function "recordings"
2021-03-21 15:01:15.854 T:10044 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-21 15:01:15.867 T:10044    INFO <general>: Skipped 2 duplicate messages..
2021-03-21 15:01:15.867 T:10044    INFO <general>: CPythonInvoker(7, C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): script successfully run
2021-03-21 15:01:15.919 T:10044    INFO <general>: Python interpreter stopped
2021-03-21 15:01:25.004 T:9148     INFO <general>: Loading skin file: MyPVRChannels.xml, load type: KEEP_IN_MEMORY
2021-03-21 15:01:26.457 T:9148     INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2021-03-21 15:01:35.114 T:8160     INFO <general>: initializing python engine.
2021-03-21 15:01:35.377 T:8160    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'urllib' has no attribute 'quote_plus'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\context.py", line 13, in <module>
                                                       channel = urllib.quote_plus(channel)
                                                   AttributeError: module 'urllib' has no attribute 'quote_plus'
                                                   -->End of Python script error report<--
```

**Comment by tbrek** [comment]
It looks like you're trying to record from context menu. I've pushed the fix for that. Pull the latest version and try.

**Comment by Weasy666** [comment]
Thx for the fast reaction.
I tried it again with the latest matrix branch. But directly after updating the plugin from the zip file, i got the following errors in the logs.

```
2021-03-23 19:15:54.208 T:9672     INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: plugin.video.iptv.recorder v0.2.1 installed
2021-03-23 19:15:54.214 T:9408     INFO <general>: initializing python engine.
2021-03-23 19:16:04.852 T:1292     INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2021-03-23 19:16:04.919 T:1832     INFO <general>: initializing python engine.
2021-03-23 19:16:06.029 T:1832     INFO <general>: [xbmcswift2] Request for "/" matches rule for function "index"
2021-03-23 19:16:06.030 T:1832  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-23 19:16:06.052 T:1832     INFO <general>: CPythonInvoker(5, C:\Users\*\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): script successfully run
2021-03-23 19:16:06.101 T:1832     INFO <general>: Python interpreter stopped
2021-03-23 19:16:15.118 T:8932     INFO <general>: initializing python engine.
2021-03-23 19:16:16.815 T:8932     INFO <general>: Skipped 1 duplicate messages..
2021-03-23 19:16:16.815 T:8932     INFO <general>: [xbmcswift2] Request for "/full_service" matches rule for function "full_service"
2021-03-23 19:16:16.833 T:8932  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-23 19:16:17.047 T:1700     INFO <general>: Skipped 1 duplicate messages..
2021-03-23 19:16:17.046 T:1700     INFO <general>: [xbmcswift2] Request for "/epg" matches rule for function "epg"
2021-03-23 19:16:17.047 T:1700  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-03-23 19:16:17.049 T:8096    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.iptv.recorder/epg
2021-03-23 19:16:17.049 T:1700     INFO <general>: CPythonInvoker(7, C:\Users\*\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py): script successfully run
2021-03-23 19:16:17.078 T:1292    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.iptv.recorder/epg) failed
2021-03-23 19:16:17.116 T:1700     INFO <general>: Python interpreter stopped
2021-03-23 19:16:18.244 T:8932    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: cannot use a string pattern on a bytes-like object
                                                   Traceback (most recent call last):
                                                     File "C:\Users\*\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3455, in <module>
                                                       plugin.run()
                                                     File "C:\Users\*\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 338, in run
                                                       items = self._dispatch(self.request.path)
                                                     File "C:\Users\*\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 312, in _dispatch
                                                       listitems = view_func(**items)
                                                     File "C:\Users\*\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 2529, in full_service
                                                       xmltv()
                                                     File "C:\Users\*\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3049, in xmltv
                                                       match = re.findall('<programme(.*?)</programme>', data, flags=(re.I|re.DOTALL))
                                                     File "C:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.0.500.0_x64__4n2hpmxwrvr6p\system\python\Lib\re.py", line 241, in findall
                                                       return _compile(pattern, flags).findall(string)
                                                   TypeError: cannot use a string pattern on a bytes-like object
                                                   -->End of Python script error report<--
                                                   
2021-03-23 19:16:18.307 T:8932     INFO <general>: Python interpreter stopped
2021-03-23 19:16:27.008 T:10804   ERROR <general>: Unable to find plugin
2021-03-23 19:16:27.008 T:10804   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://
2021-03-23 19:16:27.009 T:1292    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://) failed
2021-03-23 19:16:36.622 T:1292     INFO <general>: Loading skin file: MyPVRChannels.xml, load type: KEEP_IN_MEMORY
2021-03-23 19:16:39.721 T:1292     INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2021-03-23 19:16:42.954 T:2344     INFO <general>: initializing python engine.
2021-03-23 19:16:43.227 T:2344    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'urllib' has no attribute 'quote'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\*\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\context.py", line 13, in <module>
                                                       channel = urllib.quote(channel)
                                                   AttributeError: module 'urllib' has no attribute 'quote'
                                                   -->End of Python script error report<--
                                                   
2021-03-23 19:16:43.244 T:2344     INFO <general>: Python interpreter stopped
```

**Comment by tbrek** [comment]
It should be all fixed in the latest version.
