### ISSUE TITLE
Error in Kodi Matrix v19.1 w/ ApolloTV addon

### ISSUE THREAD

**Issue by rypz79** [tbrek/plugin.video.iptv.recorder#6]
When I go to _Addons>Video Addons>IPTV Recorder>Channel Groups_ I get IPTV plugin error.
If I select a TV show to be recorded
_Apollo Group Kodi19>TV Guide>Right click on %a TV show%>Schedule IPTV Recorder>IPTV recorder scheduled %a TV show%_   
It doesn't appear in the recording jobs _Addons>Video Addons>IPTV Recorder>Recordings_ 

IPTV Recorder v0.0.131 by primaeval,Chychy
OS Windows 10 x64

[kodi.log](https://github.com/tbrek/plugin.video.iptv.recorder/files/6834426/kodi.log)
Thanks

**Comment by tbrek** [comment]
It looks like an issue with link between epg/m3u. Possibly not matching channel_id?

I might not be able to support this plugin any longer. You could try this for archive downloading => https://github.com/tbrek/tbrek-kodi-repo

**Comment by rypz79** [comment]
> 
> 
> It looks like an issue with link between epg/m3u. Possibly not matching channel_id?
> 
> I might not be able to support this plugin any longer. You could try this for archive downloading => https://github.com/tbrek/tbrek-kodi-repo

IDUS. what do you mean by not matching channel_id??
This is the error message I get when I go to _Addons>Video Addons>IPTV Recorder>Channel Groups_
```
2021-07-17 17:53:07.964 T:6284    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'sqlite3.OperationalError'>
                                                   Error Contents: no such table: streams
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Roey\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 3450, in <module>
                                                       plugin.run()
                                                     File "C:\Users\Roey\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 338, in run
                                                       items = self._dispatch(self.request.path)
                                                     File "C:\Users\Roey\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 312, in _dispatch
                                                       listitems = view_func(**items)
                                                     File "C:\Users\Roey\AppData\Roaming\Kodi\addons\plugin.video.iptv.recorder\main.py", line 2348, in groups
                                                       channelgroups = cursor.execute("SELECT DISTINCT groups FROM streams ORDER BY groups").fetchall()
                                                   sqlite3.OperationalError: no such table: streams
                                                   -->End of Python script error report<--
```
I've installed archive downloading. IDUS how to use it to record shows from the TV guide
<img width="958" alt="Capture" src="https://user-images.githubusercontent.com/28814757/126041314-b9dfe0f1-07fc-41b4-831a-f02c8352ef49.PNG">
I guess I'll try finding a new IPTV recorder plugin 

Thanks
